plugins {
    id 'java'
    id 'org.springframework.boot' version '4.1.0'
    id 'io.spring.dependency-management' version '1.1.7'
    id('net.ltgt.errorprone') version '5.1.0'
    id("net.ltgt.nullaway") version "3.0.0"
}

group = 'org.wadajo'
version = '1.0.0-SNAPSHOT'
description = 'jspecify-spring'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testImplementation 'org.wiremock.integrations:wiremock-spring-boot:4.2.1'
    errorprone 'com.uber.nullaway:nullaway:0.13.3'
    errorprone 'com.google.errorprone:error_prone_core:2.49.0'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}

// esto evita el warning de que hay un agente inline de Mockito, explicitándolo a la JVM
tasks.withType(Test).tap {
    configureEach {
        def mockitoAgent = configurations.testRuntimeClasspath.find {
            it.name.contains('mockito-core')
        }
        if (mockitoAgent) {
            jvmArgs "-javaagent:${mockitoAgent.absolutePath}"
        }
    }
}

nullaway {
    onlyNullMarked = true
    jspecifyMode = true
}
tasks.withType(JavaCompile).configureEach {
    options.errorprone.nullaway {
        error()
    }
    options.errorprone {
        disableAllChecks = true
    }
}